name: CI

on:
  push:
    branches:
    - main
    paths-ignore:
    - '**.md'
  pull_request:
    branches:
    - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      FORCE_COLOR: true
    steps:
    - uses: actions/checkout@v2
    # Based on https://github.com/snyk/snyk/blob/master/.github/workflows/smoke-tests.yml
    
    - name: Run ShellSpec tests
      working-directory: test
      run: |
        docker run -it --rm -v "$PWD:/src" shellspec/shellspec

    - name: Check for style & bugs
      uses: ludeeus/action-shellcheck@1.1.0
      with:
        ignore: test
      env:
        SHELLCHECK_OPTS: -s bash -e SC2059 -e SC2237 -e SC2004 -e SC2001
