name: CI

on:
  push:
    branches:
    - main
    paths-ignore:
    - '**.md'
  pull_request:
    branches:
    - main
    paths-ignore:
    - '**.md'

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    env:
      FORCE_COLOR: true
    strategy:
      matrix:
        os:
        - ubuntu-latest
        include:
        - os: ubuntu-latest
    steps:
    # Based on https://github.com/snyk/snyk/blob/master/.github/workflows/smoke-tests.yml
    - name: Install Shellspec - non-windows
      if: ${{ matrix.os != 'windows' }}
      run: |
        curl -fsSL https://git.io/shellspec | sh -s -- -y
        sudo ln -s ${HOME}/.local/lib/shellspec/shellspec /usr/local/bin/shellspec
        ls -la ${HOME}/.local/lib/shellspec
        echo "shellspec symlink:"
        ls -la /usr/local/bin/shellspec
        /usr/local/bin/shellspec --version
        which shellspec
        shellspec --version
    - name: Install jq and curl on Ubuntu
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt-get install jq
        sudo apt-get install curl
    - name: Run shellspec tests
      run: shellspec -f d