name: CI

on:
  push:
    branches:
    - main
    paths-ignore:
    - '**.md'
  pull_request:
    branches:
    - main
    paths-ignore:
    - '**.md'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      FORCE_COLOR: true
    steps:
    - uses: actions/checkout@v2
    # Based on https://github.com/snyk/snyk/blob/master/.github/workflows/smoke-tests.yml
    - name: Install Shellspec
      run: |
        curl -fsSL https://git.io/shellspec | sh -s -- -y
        sudo ln -s ${HOME}/.local/lib/shellspec/shellspec /usr/local/bin/shellspec
        ls -la ${HOME}/.local/lib/shellspec
        echo "shellspec symlink:"
        ls -la /usr/local/bin/shellspec
        /usr/local/bin/shellspec --version
        which shellspec
        shellspec --version
    - name: Run shellspec tests
      working-directory: test
      run: shellspec -f d
