name: CI

on:
  push:
    branches:
    - main
    paths-ignore:
    - '**.md'
  pull_request:
    branches:
    - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      FORCE_COLOR: true
    steps:
    - uses: actions/checkout@v2
    # Based on https://github.com/snyk/snyk/blob/master/.github/workflows/smoke-tests.yml

    # Shellspec base image does not have curl, jq, awk, sed
    - name: Build Shellspec image
      working-directory: test
      run: |
        docker build . -t 'farosai/shellspec:kcov'
    
    - name: Run ShellSpec tests
      run: |
        docker run --rm \
          -v "$PWD/test:/src" \
          -v "$PWD/faros_event.sh:/faros_event.sh" \
          farosai/shellspec:kcov

    - name: Check for style & bugs
      uses: ludeeus/action-shellcheck@1.1.0
      with:
        ignore: test
      env:
        SHELLCHECK_OPTS: -s bash -e SC2059 -e SC2237 -e SC2004 -e SC2001
